include ../../dep.def
SUBPACKAGE=mmsinput
TARGET=libmmsinput.so
LOCAL_INC=-I../mmstools/inc -I../mmsconfig/inc/ -I../mmsgui/inc -I../mmsbase/inc $(SQLITE3_INC) $(CURL_INC) $(DIRECTFB_INC) $(SIGC_INC) $(LIBXML_INC)
LOCAL_LIBS=-lmmsgui -lmmstools -lmmsconfig -lmmsbase  $(DIRECTFB_LIBS) $(SIGC_LIBS) $(LIBXML_LIBS)
include ../../shlib.def
