include ../../dep.def
SUBPACKAGE=mmstools
TARGET=libmmstools.so
STATIC_TARGET=libmmstools.a
LOCAL_INC=$(SQLITE3_INC) $(CURL_INC) $(FREETDS_INC) $(DIRECTFB_INC)
LOCAL_LIBS=$(SQLITE3_LIBS) $(CURL_LIBS) $(FREETDS_LIBS) $(DIRECTFB_LIBS) -lpthread
include ../../shlib.def
