import os
import scons.helpers
Import('env idir_lib idir_inc')

libmmstools = env.SharedLibrary('../../../lib/libmmstools', Glob('*.cpp'), LIBS = "")
env.Install(idir_lib, libmmstools)

headerFiles = scons.helpers.findFiles(env['TOP_DIR'] + '/inc/mmstools', '*.h')
for header in headerFiles:
	env.Install(os.path.dirname(header.replace(env['TOP_DIR'] + '/inc/mmstools', idir_inc + '/mmstools')), header)

env['diskoSources'].append(Glob('*.cpp'))
Export('libmmstools')
