include ../../dep.def
SUBPACKAGE=mmsbase
TARGET=libmmsbase.so
LOCAL_INC=-I../mmstools/inc -I../mmsconfig/inc -I../mmsgui/inc $(SQLITE3_INC) $(CURL_INC) $(LIBXML_INC) $(DIRECTFB_INC) $(SIGC_INC)
LOCAL_LIBS=-lmmstools $(LIBXML_LIBS)
include ../../shlib.def
