import os
import scons.helpers
Import('env idir_lib idir_inc')

libmmsbase = env.SharedLibrary('../../../lib/libmmsbase', Glob('*.cpp'), LIBS = "")
env.Install(idir_lib, libmmsbase)

headerFiles = scons.helpers.findFiles(env['TOP_DIR'] + '/inc/mmsbase', '*.h')
for header in headerFiles:
	env.Install(os.path.dirname(header.replace(env['TOP_DIR'] + '/inc/mmsbase', idir_inc + '/mmsbase')), header)

env['diskoSources'].append(Glob('*.cpp'))
Export('libmmsbase')