include ../../dep.def

#check private dependencies
TARGET=taff
LOCAL_INC=$(SIGC_INC) $(DIRECTFB_INC) $(LIBXML_INC)
LOCAL_LIBS=-lmmsinfo -lmmsconfig -lmmsgui -lmmstools $(CURL_LIBS) $(SIGC_LIBS) $(LIBPNG_LIBS) $(LIBXML_LIBS) $(SQLITE3_LIBS) $(FREETDS_LIBS) $(DIRECTFB_LIBS) $(OPENSSL_LIBS) -lrt
include ../../bin.def
