include ../../dep.def

#check private dependencies
TARGET=taff
LOCAL_INC=$(DIRECTFB_INC) $(SIGC_INC) $(LIBXML_INC)
LOCAL_LIBS=-lmmstools -lmmsgui -lmmsconfig -Wl,-rpath=../lib/disko
include ../../bin.def
