Import('env idir_lib idir_inc')
libmmsconfig = env.SharedLibrary('../../../lib/libmmsconfig', Glob('*.cpp'), LIBS = "")
env.Install(idir_lib, libmmsconfig)

env.Install(idir_inc + '/mmsconfig', Glob('../../../inc/mmsconfig/*.h'))

env['diskoSources'].append(Glob('*.cpp'))
Export('libmmsconfig')