include ../../dep.def
SUBPACKAGE=mmsgui
TARGET=libmmsgui.so
LOCAL_INC=-I../mmstools/inc -I../mmsconfig/inc -I../mmsinfo/inc $(SQLITE3_INC) $(CURL_INC) $(SIGC_INC) $(DIRECTFB_INC)
LOCAL_LIBS=-lmmstools -lmmsconfig -lmmsinfo $(DIRECTFB_LIBS) $(SIGC_LIBS)
include ../../shlib.def
