include ../../dep.def
SUBPACKAGE=mmsgui
TARGET=libmmsgui.so
LOCAL_INC=-I../mmstools/inc -I../mmsconfig/inc  $(SQLITE3_INC) $(CURL_INC) $(LIBXML_INC) $(SIGC_INC) $(DIRECTFB_INC)
LOCAL_LIBS=-lmmstools -lmmsconfig  $(DIRECTFB_LIBS) $(LIBXML_LIBS) $(SIGC_LIBS)
include ../../shlib.def
