# TODO: optimize installation of headers

import os
import scons.helpers
Import('env idir_lib idir_inc idir_data libmmsinfo')

sourceFiles = scons.helpers.findFiles(env['TOP_DIR'] + '/src/mmsgui', '*.cpp')
libmmsgui = env.SharedLibrary(env['TOP_DIR'] + '/lib/libmmsgui', sourceFiles, LIBS = "")
env.Requires(libmmsgui, libmmsinfo)
env.Install(idir_lib, libmmsgui)

headerFiles = scons.helpers.findFiles(env['TOP_DIR'] + '/inc/mmsgui', '*.h')
for header in headerFiles:
	env.Install(os.path.dirname(header.replace(env['TOP_DIR'] + '/inc/mmsgui', idir_inc + '/mmsgui')), header)

share = Glob(env['TOP_DIR'] + '/share/mmsgui/*')
env.Install(idir_data + '/mmsgui', share)
Export('libmmsgui')